export const BigData = [
  {
    data: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
    data2: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
  },
  {
    data: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
    data2: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
  },
  {
    data: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
    data2: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
  },
  {
    data: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
    data2: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
  },
  {
    data: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
    data2: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
  },
  {
    data: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
    data2: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
  },
  {
    data: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
    data2: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
  },
  {
    data: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
    data2: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
  },
  {
    data: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
    data2: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
  },
  {
    data: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
    data2: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
  },
  {
    data: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
    data2: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
  },
  {
    data: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
    data2: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
  },
  {
    data: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
    data2: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
  },
  {
    data: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
    data2: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
  },
  {
    data: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
    data2: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
  },
  {
    data: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
    data2: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
  },
  {
    data: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
    data2: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
  },
  {
    data: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
    data2: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
  },
  {
    data: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
    data2: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
  },
  {
    data: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
    data2: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
  },
  {
    data: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
    data2: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
  },
  {
    data: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
    data2: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
  },
  {
    data: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
    data2: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
  },
  {
    data: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
    data2: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
  },
  {
    data: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
    data2: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
  },
  {
    data: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
    data2: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
  },
  {
    data: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
    data2: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
  },
  {
    data: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
    data2: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
  },
  {
    data: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
    data2: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
  },
  {
    data: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
    data2: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
  },
  {
    data: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
    data2: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
  },
  {
    data: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
    data2: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
  },
  {
    data: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
    data2: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
  },
  {
    data: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
    data2: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
  },
  {
    data: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
    data2: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
  },
  {
    data: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
    data2: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
  },
  {
    data: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
    data2: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
  },
  {
    data: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
    data2: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
  },
  {
    data: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
    data2: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
  },
  {
    data: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
    data2: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
  },
  {
    data: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
    data2: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
  },
  {
    data: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
    data2: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
  },
  {
    data: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
    data2: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
  },
  {
    data: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
    data2: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
  },
  {
    data: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
    data2: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
  },
  {
    data: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
    data2: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
  },
  {
    data: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
    data2: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
  },
  {
    data: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
    data2: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
  },
  {
    data: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
    data2: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
  },
  {
    data: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
    data2: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
  },
  {
    data: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
    data2: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
  },
  {
    data: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
    data2: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
  },
  {
    data: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
    data2: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
  },
  {
    data: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
    data2: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
  },
  {
    data: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
    data2: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
  },
  {
    data: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
    data2: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
  },
  {
    data: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
    data2: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
  },
  {
    data: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
    data2: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
  },
  {
    data: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
    data2: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
  },
  {
    data: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
    data2: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
  },
  {
    data: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
    data2: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
  },
  {
    data: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
    data2: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
  },
  {
    data: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
    data2: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
  },
  {
    data: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
    data2: {
      option1: 1,
      option2: 2,
      option3: 3,
      option4: 4,
      option5: 5,
    },
  },
];
